FORMAT: 1A
HOST: https://hlavoj.apiblueprint.org/

# angular.tutorial

Polls is a simple API allowing consumers to view polls and vote in them.

## Data Collection [/data]

### Temperatures [GET /data/{venueId}/temperature?from={date}&to={date}]

+ Response 200 (application/json)

        {
            "Temperature" : [ 5, 5, 5, 5, 5],
            "Humidity" :  [ 50, 50, 50, 50, 50],
            "Labels" : [ "1.1", "2.1", "3.1", "4.1", "5.1"]
        }

### Entrances  [GET /data/{venueId}/entrance?from={date}&to={date}]

+ Response 200 (application/json)

        [ 
            { "date": "1.1 8:20", "State" : 1},
            { "date": "1.1 8:30", "State" : 1},
            { "date": "1.1 8:40", "State" : 1}, 
            { "date": "1.1 8:50", "State" : 1}, 
            { "date": "1.1 9:00", "State" : 0}, 
            { "date": "1.1 9:10", "State" : 0}, 
            { "date": "1.1 9:20", "State" : 1}, 
            { "date": "1.1 9:30", "State" : 1}, 
            { "date": "1.1 9:40", "State" : 1}, 
            { "date": "1.1 9:50", "State" : 0}, 
            { "date": "1.1 10:00", "State" : 1}, 
            { "date": "1.1 10:10", "State" : 1}, 
        ]

## Lights Collection [/light]

### Lights list [GET /light?from={date}&to={date}]

+ Response 200 (application/json)

        [
            {   
                "id": 1, 
                "turnOn" : 1,
                "intensity" : 80,
                "color": "#ffffff" 
            },{   
                "id": 2, 
                "turnOn" : 1,
                "intensity" : 80,
                "color": "#ffffff" 
            },
        ]

### Light detail [GET /light/{lightId}]

+ Response 200 (application/json)

        {   
            "id": 1, 
            "turnOn" : 1,
            "intensity" : 80,
            "color": "#ffffff" 
        }

### Light Set [PUT /light/{lightId}]

+ Response 200 (application/json)

        {   
            "turnOn" : 1,
            "intensity" : 80,
            "color": "#ffffff" 
        }


### Light schedule [POST /light/{lightId}/schedule]

+ Response 200 (application/json)

        {
            "date": "1.1 8:20",
            "turnOn" : 1,
            "intensity" : 80,
            "color": "#ffffff"
        }


## Authentication  [/auth]

### Login [GET /auth/login]

+ Response 200 (application/json)